cadip:
  auth:
    type: GenericAuth
    method: basic
    credentials:
        username: test
        password: test
  products:
    GENERIC_PRODUCT_TYPE:
      productType: '{productType}'

  search:
    type: ODataV4Search
    api_endpoint: 'http://127.0.0.1:5000/Files'
    need_auth: true
    results_entry: responses | $
    metadata_mapping:
        id:
            - null
            - '$.Id'
        Name:
            - null
            - '$.Name'
        SessionID:
            - null
            - '$.SessionID'
        Channel:
            - null
            - '$.Channel'
        BlockNumber:
            - null
            - '$.BlockNumber'
        FinalBlock:
            - null
            - '$.FinalBlock'
        PublicationDate:
            - null
            - '$.PublicationDate'
        EvictionDate:
            - null
            - '$.EvictionDate'
        Size:
            - null
            - '$.Size'
        Retransfer:
            - null
            - '$.Retransfer'
        # Eodag Specific map
        startTimeFromAscendingNode:
            - null
            - '$.PublicationDate'
        completionTimeFromAscendingNode:
            - null
            - '$.PublicationDate'
        geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
        downloadLink: 'http://127.0.0.1:5000/Files({id})/$value'
        title: '$.Name'

    free_text_search_operations:
      $filter:
        union: ' OR '
        wrapper: '"{}"'
        operations:
            and:
              - 'PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}'
              - 'PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}'

    pagination:
      max_items_per_page: 1000
      next_page_url_tpl: '{url}?{search}&$top={items_per_page}'
      total_items_nb_key_path: '$.total'

  download:
    type: HTTPDownload
    base_uri: 'https://127.0.0.1:5000/Files'
    metadata_mapping:
        uid: '$.Id'
        downloadLink: 'http://127.0.0.1:5000/Files({uid})/$value'

cadip_session:
  auth:
    type: GenericAuth
    method: basic
    credentials:
      username: test
      password: test
  products:
    GENERIC_PRODUCT_TYPE:
      productType: "{productType}"

  search:
    type: ODataV4Search
    api_endpoint: "http://127.0.0.1:5000/Sessions"
    need_auth: true
    results_entry: responses | $
    metadata_mapping:
      id:
        - null
        - "$.Id"
      SessionIds:
        - null
        - "$.SessionId"
      SessionId:
        - null
        - "$.SessionId"
      NumChannels:
        - null
        - "$.NumChannels"
      PublicationDate:
        - null
        - "$.PublicationDate"
      platform:
        - null
        - "$.Satellite"
      platforms:
        - null
        - "$.Satellite"
      StationUnitId:
        - null
        - "$.StationUnitId"
      DownlinkOrbit:
        - null
        - "$.DownlinkOrbit"
      AcquisitionId:
        - null
        - "$.AcquisitionId"
      AntennaId:
        - null
        - "$.AntennaId"
      FrontEndId:
        - null
        - "$.FrontEndId"
      Retransfer:
        - null
        - "$.Retransfer"
      AntennaStatusOK:
        - null
        - "$.AntennaStatusOK"
      FrontEndStatusOK:
        - null
        - "$.FrontEndStatusOK"
      PlannedDataStart:
        - null
        - "$.PlannedDataStart"
      PlannedDataStop:
        - null
        - "$.PlannedDataStop"
      DownlinkStart:
        - null
        - "$.DownlinkStart"
      DownlinkStop:
        - null
        - "$.DownlinkStop"
      DownlinkStatusOK:
        - null
        - "$.DownlinkStatusOK"
      DeliveryPushOK:
        - null
        - "$.DeliveryPushOK"
      # Eodag Specific map
      startTimeFromAscendingNode:
        - null
        - "$.PublicationDate"
      completionTimeFromAscendingNode:
        - null
        - "$.PublicationDate"
      geometry: "POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))"
      title: "$.Name"

    free_text_search_operations:
      $filter:
        union: " OR "
        wrapper: '"{}"'
        operations:
          and:
            - "SessionId in {SessionIds}"
            - "SessionId eq {SessionId}"
            - "Satellite eq {platform}"
            - "Satellite in {platforms}"
            - "PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}"
            - "PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}"

    pagination:
      max_items_per_page: 1000
      next_page_url_tpl: "{url}?{search}&$top={items_per_page}"
      total_items_nb_key_path: "$.total"

  download:
    type: HTTPDownload
    base_uri: "https://127.0.0.1:5000/Sessions"
    metadata_mapping:
      uid: "$.Id"
      downloadLink: "http://127.0.0.1:5000/Files({uid})/$value"
