# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE WAS AUTOMATICALLY CREATED FROM:
#  - rs-server/services/cadip/config/cadip_search_config.template.yaml
#  - rs-server/resources/sync_config_files.py
# DON'T MODIFY IT DIRECTLY !

collections:
  - id: s1_ins
    station: ssc
    query:
      Satellite: ['S1A','S1C']
      StationId: INS_
    stac_extensions: []
    title:  'Sentinel-1 Inuvik CADIP'
    description: 'Sentinel-1 CADIP sessions and chunk downloaded to Inuvik station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_ins.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Inuvik'

  - id: s2_ins
    station: ssc
    query:
      Satellite: ['S2A','S2B','S2C']
      StationId: INS_
    stac_extensions: []
    title:  'Sentinel-2 Inuvik CADIP'
    description: 'Sentinel-2 sessions and chunk downloaded to Inuvik station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s2_ins.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S2 Inuvik'

  - id: s1_kse
    station: ssc
    query:
      Satellite: ['S1A','S1C']
      StationId: KSE_
    stac_extensions: []
    title:  'Sentinel-1 Kiruna CADIP'
    description: 'Sentinel-1 CADIP sessions and chunk downloaded to Kiruna (Esrange) station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_kse.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Kiruna'

  - id: s2_kse
    station: ssc
    query:
      Satellite: ['S2A','S2B','S2C']
      StationId: KSE_
    stac_extensions: []
    title:  'Sentinel-2 Kiruna CADIP'
    description: 'Sentinel-2 sessions and chunk downloaded to Kiruna (Esrange) station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s2_kse.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S2 Kiruna'

  - id: s1_par
    station: ssc
    query:
      Satellite: ['S1A','S1C']
      StationId: PAR_
    stac_extensions: []
    title:  'Sentinel-1 Punta Arenas CADIP'
    description: 'Sentinel-1 CADIP sessions and chunk downloaded to Punta Arenas station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_par.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Punta Arenas'

  - id: s2_par
    station: ssc
    query:
      Satellite: ['S2A','S2B','S2C']
      StationId: PAR_
    stac_extensions: []
    title:  'Sentinel-2 Punta Arenas CADIP'
    description: 'Sentinel-2 sessions and chunk downloaded to Punta Arenas station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s2_par.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S2 Punta Arenas'

  - id: s1_mti
    station: mti
    query:
      Satellite: ['S1A','S1C']
    stac_extensions: []
    title:  'Sentinel-1 Matera CADIP '
    description: 'Sentinel-1 sessions and chunk downloaded to Matera station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_mti.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Matera'

  - id: s1_sgs
    station: sgs
    query:
      Satellite: ['S1A','S1C']
    stac_extensions: []
    title:  'Sentinel-1 Svalbard CADIP'
    description: 'Sentinel-1 sessions and chunk downloaded to Svalbard station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_sgs.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Svalbard'

  - id: s2_sgs
    station: sgs
    query:
      Satellite: ['S2A','S2B','S2C']
    stac_extensions: []
    title:  'Sentinel-2 Svalbard CADIP'
    description: 'Sentinel-2 sessions and chunk downloaded to Svalbard station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s2_sgs.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S2 Svalbard'

  - id: s3_sgs
    station: sgs
    query:
      Satellite: ['S3A','S3B']
    stac_extensions: []
    title:  'Sentinel-3 Svalbard CADIP'
    description: 'Sentinel-3 sessions and chunk downloaded to Svalbard station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s3_sgs.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S3 Svalbard'

  - id: s1_mps
    station: mps
    query:
      Satellite: ['S1A','S1C']
    stac_extensions: []
    title:  'Sentinel-1 Maspalomas CADIP'
    description: 'Sentinel-1 sessions and chunk downloaded to Maspalomas station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_mps.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Maspalomas'

  - id: s1_nsg
    station: nsg
    query:
      Satellite: ['S1A','S1C']
    stac_extensions: []
    title:  'Sentinel-1 Neustrelitz CADIP sessions'
    description: 'Sentinel-1 sessions and chunk downloaded to Neustrelitz station'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
        type: 'application/pdf'
      - rel: describedby
        href: 'https://sentiwiki.copernicus.eu/web/copernicus-operations#CopernicusOperations-DataAcquisition'
        title: 'Data Acquisition'
        type: 'text/html'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/sentinel-1'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
    assets:
      thumbnail:
        href: 'https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/images/cadip/s1_nsg.jpg'
        type: 'image/jpeg'
        roles:
          - thumbnail
        title: 'S1 Neustrelitz'
