require 'asciidoctor'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/index.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/index.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''images'' stylesheet@=''asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/environment/installation.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/environment/installation.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/environment/description.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/environment/description.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/background/workflow.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/background/workflow.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/code-style.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/code-style.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../images'' stylesheet@=''../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/doc-generation/how-to.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/doc-generation/how-to.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/doc-generation/description.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/doc-generation/description.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/api/python/html/index.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/api/python/html/index.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../../images'' stylesheet@=''../../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/api/rest/index.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/api/rest/index.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/background/tree-structure.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/background/tree-structure.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/background/ci.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/background/ci.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
Asciidoctor.convert_file '/home/runner/work/rs-server/rs-server/dist/doc/intermediate/dev/design/design.adoc', to_file: '/home/runner/work/rs-server/rs-server/dist/doc/output/dev/design/design.html', safe: :unsafe, backend: 'html5', mkdirs: true, basedir: '/home/runner/work/rs-server/rs-server/dist/doc/intermediate', attributes: 'imagesdir@=''../../images'' stylesheet@=''../../asciidoxy-no-toc.css'' multipage'
logger = Asciidoctor::LoggerManager.logger
exit 1 if (logger.respond_to? :max_severity) &&
  logger.max_severity &&
  logger.max_severity >= (::Logger::Severity.const_get 'FATAL')
