= Change log
:hardbreaks:

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/[Keep a Changelog].

The RS-SERVER is delivered with a version using 3 digits: X.Y.Z

* X is increased when the global scope is impacted. For example, if the message brocker is changed.
* Y is increased when a major feature is added/impacted (and X is not increased). For example, XBIP ingeqtion is remplaced by CADIP.
* Z is increased when a minor feature is added/impacted (and X and Y are not increased) . For example, the request timeout is changed.

== [Unreleased]

=== Added

* initialize technical documentation
* initialize python project

=== Fixed

None

=== Changed

None

== [1.0a3] - 2024-01-16

=== Added

* RSPY-14: Add endpoint "download cadu" to CADIP backend server
* RSPY-16: Develop CADIP backend server with first endpoint "get cadu"
* RSPY-53: Develop Catalog backend server
* RSPY-72: Add endpoint "CADU status" to CADIP backend server
