[project]
name = "rs-server"
version = "0.1.0"

[tool.poetry]
name = "rs-server"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

packages = [
    { include = "src" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.11.0,<4.0"
moto = "==4.2.8"
boto3 = "==1.28.85"
botocore = "==1.31.85"
flask-cors = "^4.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
black = "^23.10.1"
ruff = "^0.1.3"
mypy = "^1.6.1"
pre-commit = "^3.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
# This is mandatory for pytest-docker
# to have a pytest.rootdir set to project.rootdir


[tool.ruff]
line-length = 120 # is it useful if not using ruff formatter ?

[tool.ruff.lint]
# F = PyFlake
# E = pycodestyle
# I = isort
# N = pep8 naming
# D = pydocstyle
# PL = pylint
select = ["F", "E", "I", "N", "D", "PL"]

# TODO try to replace black by ruff formatter
