[project]
name = "rs-server"
version = "0.0.0" # see: https://github.com/mtkennerly/poetry-dynamic-versioning

[tool.poetry]
name = "rs-server"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.adoc"

packages = [
    { include = "rs_server" },
    { include = "rs_server_common", from = "services/common"},
    { include = "rs_server_cadip", from = "services/cadip" },
    { include = "tests", format = "sdist" },
    { include = "services/common/tests", format = "sdist" },
    { include = "services/cadip/tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.11.0,<4.0"
# Are all these dependencies mandatory ?
moto = "==4.2.8"
boto3 = "==1.28.85"
botocore = "==1.31.85"
prefect = "^2.14.11"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
pytest-error-for-skips = "^2.0.2"
black = "^23.10.1"
mypy = "^1.6.1"
pre-commit = "^3.5.0"
types-requests = "^2.31.0.10"
flake8 = "^6.1.0"
bandit = "^1.7.5"
safety = "^2.3.5"
pylint = "^3.0.3"
flake8-pyproject = "^1.2.3"
flask = "^3.0.0"
flask-cors = "^4.0.0"
pytest-asyncio = "^0.23.2"

[tool.poetry-dynamic-versioning] # needs: poetry self add "poetry-dynamic-versioning[plugin]"
enable = true
tagged-metadata = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]

[tool.mypy]
warn_redundant_casts = true
# Force analyze of partially annotate function signatures
check_untyped_defs = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 120
# per-file-ignores = [
#     '__init__.py:F401',
# ]

[tool.pylint.messages_control]
max-line-length=120
