# Copyright 2023-2025 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "rs-server"
dynamic = ["version"] # see: https://github.com/mtkennerly/poetry-dynamic-versioning

[tool.poetry]
name = "rs-server"
version = "0.0.0"
description = "Copernicus Sentinel rs-server."
license = "Apache-2.0"
authors = ["ESA under contract with Airbus and CS <ops_coprs@airbus.com>"]
readme = "README.md"
homepage = "https://home.rs-python.eu/"
repository = "https://github.com/RS-PYTHON/rs-server"
documentation = "https://home.rs-python.eu/rs-documentation/rs-server/docs/doc/"
keywords = ["stac", "copernicus", "sentinel", "processing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: FastAPI",
    "Framework :: OpenTelemetry",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Image Processing"
]

packages = [

    { include = "rs_server_adgs", from = "services/adgs"},
    { include = "rs_server_cadip", from = "services/cadip" },
    { include = "rs_server_catalog", from = "services/catalog" },
    { include = "rs_server_common", from = "services/common"},
    { include = "rs_server_frontend", from = "services/frontend"},
    { include = "rs_server_staging", from = "services/staging"},
    { include = "rs_server_edrs", from = "services/edrs" },

    { include = "tests", format = "sdist" },
    # { include = "services/adgs/tests", format = "sdist" },
    # { include = "services/cadip/tests", format = "sdist" },
    { include = "services/catalog/tests", format = "sdist" },
    { include = "services/common/tests", format = "sdist" },
    { include = "services/frontend/tests", format = "sdist" },
    { include = "services/staging/tests", format = "sdist" },
]

# This root project is not used in release production.
# It's only used by the CI/CD to run pytest, pylint, mypy etc... on the whole github project.

# All the dependencies for release are set in the sub-projects
[tool.poetry.dependencies]
python = ">=3.13,<4"
rs-server-adgs = {path = "services/adgs", develop = true}
rs-server-prip = {path = "services/prip", develop = true}
rs-server-cadip = {path = "services/cadip", develop = true}
rs-server-edrs = {path = "services/edrs", develop = true}
rs-server-catalog = {path = "services/catalog", develop = true}
rs-server-common = {path = "services/common", develop = true}
rs-server-frontend = {path = "services/frontend", develop = true}
rs-server-staging = {path = "services/staging", develop = true}

[tool.poetry.group.dev]
optional = true

# All the dev dependencies are set here so they can be used by the CI.
[tool.poetry.group.dev.dependencies]
pygeoapi = ">=0.21"
# pygeoapi = { git = "https://github.com/geopython/pygeoapi.git", rev = "1eb24cb" } # hardcode commit id from master
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"
pytest-cov = "^7.0.0"
pytest-docker = "^3.2.3"
pytest-error-for-skips = "^2.0.2"
pytest-httpx = ">=0.35,<0.36"
pytest-mock = "^3.15.1"
black = "^25.1.0"
mypy = "^1.17.1"
pre-commit = "^4.5.1"
types-requests = "^2.32.4.20250809"
flake8 = "^7.1.2"
bandit = "^1.9.1"
safety = "^3.6.0"
pylint = "^4.0.2"
flake8-pyproject = "^1.2.3"
httpx = "^0.28.1"
sphinx = "^8.2.3"
sphinx-rtd-theme = "^3.0.1"
sqlalchemy-utils = "^0.42.0"
click = "8.3.1"
responses = "^0.25.8"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
metadata = false

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
# https://github.com/CS-SI/eodag/issues/1623
filterwarnings = [
    "ignore::DeprecationWarning:pkg_resources",
    "ignore::DeprecationWarning:eodag.plugins.manager",
    "ignore::DeprecationWarning:pydantic._internal._config",
    "ignore::DeprecationWarning:pydantic.fields"
]

[tool.mypy]
warn_redundant_casts = true
# Force analyze of partially annotate function signatures
check_untyped_defs = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 120
extend-ignore = [
    "E203" # whitespace before ':'
]
# per-file-ignores = [
#     '__init__.py:F401',
# ]

[tool.pylint]
max-line-length = 120
disable = [
    "logging-fstring-interpolation",  # Logging f-string interpolation
    "R0917",  # Too many positional arguments
    "E0401", # import-error
    "R0902", # too-many-instance-attributes
    "R0913",  # too-many-arguments
    "too-many-locals",
    "not-context-manager",
    "too-many-lines",
    "too-many-public-methods",
]
ignore-paths = '^docs/.*$'

# Only add notes as comments that are not checked for errors.
notes = ["XXX"]  # No errors on TODO and FIXME

min-similarity-lines = 10  # Minimum lines number of a similarity

[tool.bandit.assert_used]
skips = ['*/test_*.py', '*/conftest.py']
