= rs-server

// Note: links to branch 'develop'
image::https://sonarqube.ops-csc.com/api/project_badges/measure?branch=develop&project=RS-PYTHON_rs-server_AYw0m7ixvQv-JMsowILQ&metric=alert_status&token=sqb_c9241ef82ea91a8e9a9b604570f834f622dfed05[Quality Gate Status,link="https://sonarqube.ops-csc.com/dashboard?id=RS-PYTHON_rs-server_AYw0m7ixvQv-JMsowILQ&branch=develop"]

This repository contains all the python libraries allowing to build Copernicus processing chains.

== Use the rs-server

:leveloffset: +2
include::docs/users/installation.adoc[]
include::docs/users/functionalities.adoc[]
include::docs/users/configuration.adoc[]
:leveloffset: -2

== Develop the rs-server

All you want to know when you are a rs-server developer.

The documentation is organized in 4 sections :

* <<_getting_started>> provides tutorials helping you start coding on rs-server.
* <<_how_to_guides>> are practical procedures for developer
* <<_reference_guides>> give you technical information about the code and software API
* <<_additional_information>> provides background information, design,...

=== Getting started

:leveloffset: 3

include::docs/dev/environment/installation.adoc[]

:leveloffset: 0

==== The next steps

The <<_development_environment_description>> can provide you with more details about the environment.
The <<_project_tree_structure>> explains how the project is organized.
The <<_team_workflow>> describes the workflow followed by developers to implement stories.
You may also want to read the <<_coding_style>>.

=== How-to guides

NOTE: This section will include the awesome and useful procedures of the dev team

=== Reference guides

NOTE: Some other reference guides will be added (api, specific guidelines,...)

:leveloffset: 3

include::docs/dev/code-style.adoc[]

:leveloffset: 0

=== Additional information

:leveloffset: +3

include::docs/dev/background/tree-structure.adoc[]
include::docs/dev/environment/description.adoc[]
include::docs/dev/background/workflow.adoc[]
include::docs/dev/background/ci.adoc[]
include::docs/dev/design/design.adoc[]

:leveloffset: -3

== Links

- Project homepage: https://github.com/RS-PYTHON/rs-server
- Repository: https://github.com/RS-PYTHON/rs-server
- Issue tracker: https://github.com/RS-PYTHON/rs-server/issues
-- In case of sensitive bugs like security vulnerabilities, please contact
    my@email.com directly instead of using issue tracker. We value your effort
    to improve the security and privacy of this project!

== Licensing

The code in this project is licensed under Apache License 2.0.
