# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: tag-push-docker
description: Tag and push Docker images

inputs:
  old_docker_images:
    description: Old Docker images to retag, as a comma-separated list e.g. 'image1:old-tag,image2:old-tag'
    required: true
  new_tags:
    description: New tags to add to old Docker images, as a comma-separated list e.g. 'new-tag1,new-tag2'
    required: false

runs:
  using: "composite"
  steps:
      - id: set-env
        env:
          OLD_DOCKER_IMAGES: ${{ inputs.old_docker_images }}
          NEW_TAGS: ${{ inputs.new_tags }}
        run: |
          set -x

          # Pull each pushed image in parallel
          for old_image in ${OLD_DOCKER_IMAGES//,/ }; do
            docker pull "$old_image" &
          done
          wait

          # Add new tags and push in parallel
          for old_image in ${OLD_DOCKER_IMAGES//,/ }; do
            for new_tag in ${NEW_TAGS//,/ }; do

              # Only alphanumeric characters, . - and _ are allowed in docker image tags.
              # Replace other characters by -
              new_tag=$(sed "s/[^a-zA-Z0-9\.\-\_]/-/g" <<< "$new_tag")

              # Remove the tag from the last image, see: https://stackoverflow.com/a/19482947
              # and add the new tag
              new_image="${old_image%:*}:${new_tag}"

              docker tag "$old_image" "$new_image"
              docker push "$new_image" &
            done
          done
          wait
        shell: bash
