name: publish-docker
description: Publish Docker image

inputs:
  dockerfile:
    description: Dockerfile path
    required: true
  build_context_path:
    description: "'docker build' context path"
    required: true
  version_name:
    description: Version name e.g. 1.2.3a4.dev1a2b3c4d
    required: true
  github_token:
    description: secrets.GITHUB_TOKEN
    required: true

# Copied from https://github.com/COPRS/reference-system-software/blob/dependencies
# and https://github.com/COPRS/reference-system-software/blob/trivy-security-scan-v1/action.yml

runs:
  using: "composite"
  steps:

    # Replace invalid characters in the Docker version name, e.g. 1.2.3a4+dev1a2b3c4d becomes 1.2.3a4.dev1a2b3c4d
    # Then we can use ${{ inputs.docker_version_name }}
    - run: echo "docker_version_name=$(echo ${{ inputs.version_name }} | tr + .)" >> $GITHUB_ENV
      shell: bash

    # Extract metadata from Git reference and GitHub events
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE_NAME }}

    # Checkout code from the current branch and build Docker image.
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./whl
        file: ${{ inputs.dockerfile }}
        load: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.docker_version_name }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false # push after the security scans below

    - name: Run Trivy vulnerability scanner SARIF
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.docker_version_name }}
        format: sarif
        output: trivy-results.sarif
        #severity: HIGH,CRITICAL
        #timeout: '30m'

    - name: Save scan results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-results.sarif
        path: trivy-results.sarif

    - name: Upload scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always() # run even if the scan returned a non-zero exit code
      with:
        sarif_file: trivy-results.sarif
        #category:

    - name: Log into Docker registry ${{ env.DOCKER_REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    # - name: Push Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.docker_version_name }}
