# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: publish-docker
description: Publish Docker image

inputs:
  dockerfile:
    description: Dockerfile path
    required: true
  build_context_path:
    description: "'docker build' context path"
    required: true
  image_basename:
    description: Docker image base name
    default: ${{ github.repository }} # = owner/repository-name
  image_suffix:
    description: Docker image name suffix e.g. _services-cadip
    required: true
  version_name:
    description: Version name e.g. 1.2.3a4.dev1a2b3c4d
    required: true
  dockerhub_username:
    description: vars.DOCKERHUB_USERNAME
    required: true
  dockerhub_token:
    description: secrets.DOCKERHUB_TOKEN
    required: true
  github_token:
    description: secrets.GITHUB_TOKEN
    required: true
  docker_tag:
    description: Tag the docker image
    required: false
  branch_name:
    description: Current git branch name
    required: true
  debug_mode:
    description: Add debug tools to the docker image
    required: false
  build_args:
    description: List of build-time variables
    required: false

outputs:
  docker_image:
    description: Docker image name:tag
    value: ${{ steps.docker_image.outputs.docker_image }}

runs:
  using: "composite"
  steps:

    # Login to Docker Hub to increase pull quota from 100 to 200 per 6 hours
    - name: Log into Docker Hub
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Log into GitHub Container Registry
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    # Replace invalid characters in the Docker version name, e.g. 1.2.3a4+dev1a2b3c4d becomes 1.2.3a4.dev1a2b3c4d
    # Then we can use ${{ inputs.docker_version_name }}
    - env:
        VERSION_NAME: ${{ inputs.version_name }}
      run: echo "docker_version_name=$(echo $VERSION_NAME | tr + .)" >> $GITHUB_ENV
      shell: bash

    # Full Docker image name:tag as ghcr.io/RS-PYTHON/rs-server<suffix>:<version> in lowercase
    - id: docker_image
      env:
        DOCKER_IMAGE: "${{ env.DOCKER_REGISTRY }}/${{ inputs.image_basename }}${{ inputs.image_suffix }}:${{ env.docker_version_name }}"
      run: |
        docker_image=${DOCKER_IMAGE,,} # lowercase
        echo docker_image=${docker_image} >> $GITHUB_ENV
        echo docker_image=${docker_image} >> $GITHUB_OUTPUT
      shell: bash

    # Extract metadata from Git reference and GitHub events
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }} # ghcr.io/RS-PYTHON/rs-server

    # Replace some parts of the Dockerfile depending on wether we're in debug mode or not.
    # It would be cleaner to use 'if' blocks in the Dockerfile but this doesn't exist...
    - name: Configure Dockerfile for debug mode
      env:
        DEBUG_MODE: ${{ inputs.debug_mode }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        DOCKERFILE: ${{ inputs.dockerfile }}
      run: |
        set -x
        if [[ $DEBUG_MODE == true ]]; then
          commands=$(cat << EOF
        USER root
        COPY ./git_debug_image.sh ./restore-apt.sh /usr/local/bin/
        # Use ';' not '&&' because they are not well handled by awk.
        RUN set -e; \
            cd /usr/local/bin/; \
            chmod u+x ./git_debug_image.sh ./restore-apt.sh; \
            ./git_debug_image.sh $BRANCH_NAME; \
            rm -f ./git_debug_image.sh ./restore-apt.sh
        WORKDIR /home/user/rs-server
        EOF
          )
          # Use awk instead of sed for multiline replace, see: https://stackoverflow.com/a/10107668
          awk -v r="$commands" '{gsub(/# \[DEBUG_MODE_COMMANDS\]/,r)}1' $DOCKERFILE > tmp
          mv tmp $DOCKERFILE
          sed -i "s@\[DEBUG_MODE_RELOAD\]@--reload@g" $DOCKERFILE
          sed -i "s@\[DEBUG_MODE_RELOAD_FRONTEND\]@--reload@g" $DOCKERFILE
          sed -i "s@# \[DEBUG_MODE_RELOAD_CATALOG\]@ENV RELOAD=true@g" $DOCKERFILE
        else
          sed -i "s@# \[DEBUG_MODE_COMMANDS\]@@g" $DOCKERFILE
          sed -i "s@, \"\[DEBUG_MODE_RELOAD\]\"@@g" $DOCKERFILE
          sed -i "s@\[DEBUG_MODE_RELOAD_FRONTEND\]@@g" $DOCKERFILE
          sed -i "s@# \[DEBUG_MODE_RELOAD_CATALOG\]@@g" $DOCKERFILE
        fi
        cat $DOCKERFILE
      shell: bash

    # Checkout code from the current branch and build Docker image.
    - name: Build Docker image
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        context: ${{ inputs.build_context_path }}
        file: ${{ inputs.dockerfile }}
        load: true
        tags: ${{ env.docker_image }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false # push after the security scans below
        build-args: ${{ inputs.build_args }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
      with:
        version: v0.69.1
        image-ref: ${{ env.docker_image }}
        format: sarif
        output: trivy-results-docker.sarif
        exit-code: 0
        limit-severities-for-sarif: true
        severity: HIGH,CRITICAL
        #timeout: '30m'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: trivy-results-docker.sarif
        category: ${{ inputs.image_basename }}${{ inputs.image_suffix }}

    - name: Display link to Trivy results
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |

          set -x

          # If this is not a pull request, the query is "is:open+branch:branch_name"
          if [[ "$GITHUB_REF_NAME" != *merge* ]]; then
            query="is:open+branch:$GITHUB_REF_NAME"

          # Else the ref_name is e.g. '13/merge'. Change it into 'pr:13'
          else
            query=$(sed "s|\(.*\)/merge|pr:\1|g" <<< "$GITHUB_REF_NAME")
          fi

          echo "Trivy scan results:" \
          "https://github.com/${GITHUB_REPOSITORY}/security/code-scanning?query=${query}" \
          >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Push Docker image
      env:
        DOCKER_IMAGE: ${{ env.docker_image }}
      run: docker push ${DOCKER_IMAGE}
      shell: bash

    # Add a docker image tag and push it into the registry.
    - name: Push Docker tag e.g. 'latest'
      if: always()
      env:
        DOCKER_TAG: ${{ inputs.docker_tag }}
        DOCKER_IMAGE: ${{ env.docker_image }}
      run: | # use sed to replace the last :<tag> by :docker_tag
        set -x
        if [[ ${DOCKER_TAG}test != test ]]; then # if variable is defined and not empty
          docker_image_tag=$(sed "s|\(:[^:]*\)|:${DOCKER_TAG}|g" <<< ${DOCKER_IMAGE})
          docker tag ${DOCKER_IMAGE} ${docker_image_tag}
          docker push ${docker_image_tag}
        fi
      shell: bash
