# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.0
info:
  title: RS Staging API
  version: 1.0.0
paths:
  /processes:
    get:
      summary: Get a list of processes
      responses:
        '200':
          description: Returns list of all available processes from config.
          content:
            application/json:
              schema:
                $ref: './processList.yaml'
  /processes/{process_id}:
    get:
      summary: Get information on a specific process
      parameters:
        - name: process_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a description of a specific process
          content:
            application/json:
              schema:
                $ref: './process.yaml'
  /processes/{process_id}/execution:
    post:
      summary: Get information on a specific process
      parameters:
        - name: process_id
          in: path
          required: true
          schema:
            type: string
      # Here both the request and the response need to be validates according to yaml schemas
      requestBody:
        description: Check the body from the request used to execute the process
        required: true
        content:
          application/json:
            schema:
              $ref: './execute.yaml'
            examples:
              example1:
                $ref: '#/components/examples/AsyncExecuteBodyExample'
      responses:
        '200':
          description:  Result of synchronous execution
          content:
            application/json:
              schema:
                $ref: './statusInfo.yaml'
        '201':
          description: Started asynchronous execution. Created job.
          content:
            application/json:
              schema:
                $ref: './statusInfo.yaml'
  /jobs:
    get:
      summary: Returns the status of all jobs.
      responses:
        '200':
          description: Returns the status of all jobs.
          content:
            application/json:
              schema:
                $ref: './jobList.yaml'
  /jobs/{job-id}:
    get:
      summary: Returns the status of a job.
      parameters:
        - name: job-id
          in: path
          description: local identifier of a job
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The status of a job.
          content:
            application/json:
              schema:
                $ref: 'statusInfo.yaml'
    delete:
      summary: Deletes a specific job.
      parameters:
        - name: job-id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the job to be deleted.
      responses:
        '200':
          description: Deletes a specific job.
          content:
            application/json:
              schema:
                $ref: './statusInfo.yaml'
  /jobs/{job-id}/results:
    get:
      summary: Returns the results of a given job
      parameters:
        - name: job-id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns the status of all jobs.
          content:
            application/json:
              schema:
                $ref: './results.yaml'
components:
  examples:
    AsyncExecuteBodyExample:
      summary: Example of an execution request
      value:
        inputs:
          collection: "my_test_collection"
          items:
            value:
              type: "FeatureCollection"
              features:
                - id: "CADU1.raw"
                  type: "Feature"
                  links:
                    - rel: "collection"
                      type: "application/json"
                      href: "http://127.0.0.1:8003/collections/TestUser_s1_chunk"
                    - rel: "parent"
                      type: "application/json"
                      href: "http://127.0.0.1:8003/collections/TestUser_s1_chunk"
                    - rel: "root"
                      type: "application/json"
                      href: "http://127.0.0.1:8003/"
                    - rel: "self"
                      type: "application/geo+json"
                      href: "http://127.0.0.1:8003/collections/TestUser_s1_chunk/items/CADU1.raw"
                  assets:
                    CADU1.raw:
                      href: "https://rs-server/catalog/TestUser/collections/s1_chunk/items/CADU1.raw/download/file"
                      alternate:
                        s3:
                          href: "s3://rs-cluster-catalog/stations/CADIP/CADU1.raw"
                      file:size: 58
                  geometry:
                    type: "Polygon"
                    coordinates:
                      - [[180, -90], [180, 90], [-180, 90], [-180, -90], [180, -90]]
                  bbox: [-180.0, -90.0, 180.0, 90.0]
                  collection: "TestUser_s1_chunk"
                  properties:
                    owner: "TestUser"
                    created: "2020-01-05T18:52:56.165Z"
                    cadip:id: "d52278c7-75e5-4cb5-b8e4-0a75b83e9a2d"
                    datetime: "1970-01-01T12:00:00.000Z"
                    cadip:channel: 1
                    cadip:session_id: "S1A_20200105072204051312"
                    cadip:block_number: 1
                  stac_version: "1.0.0"
                  stac_extensions:
                    - "https://stac-extensions.github.io/file/v2.1.0/schema.json"
                    - "https://stac-extensions.github.io/alternate-assets/v1.1.0/schema.json"
                - id: "CADU2.raw"
                  type: "Feature"
                  links:
                    - rel: "collection"
                      type: "application/json"
                      href: "http://127.0.0.1:8003/collections/TestUser_s1_chunk"
                    - rel: "parent"
                      type: "application/json"
                      href: "http://127.0.0.1:8003/collections/TestUser_s1_chunk"
                    - rel: "root"
                      type: "application/json"
                      href: "http://127.0.0.1:8003/"
                    - rel: "self"
                      type: "application/geo+json"
                      href: "http://127.0.0.1:8003/collections/TestUser_s1_chunk/items/CADU2.raw"
                  assets:
                    CADU2.raw:
                      href: "https://rs-server/catalog/TestUser/collections/s1_chunk/items/CADU2.raw/download/file"
                      alternate:
                        s3:
                          href: "s3://rs-cluster-catalog/stations/CADIP/CADU2.raw"
                      file:size: 58
                  geometry:
                    type: "Polygon"
                    coordinates:
                      - [[180, -90], [180, 90], [-180, 90], [-180, -90], [180, -90]]
                  bbox: [-180.0, -90.0, 180.0, 90.0]
                  collection: "TestUser_s1_chunk"
                  properties:
                    owner: "TestUser"
                    created: "2020-01-06T18:52:56.165Z"
                    cadip:id: "d52278c7-75e5-4cb5-b8e4-0a75b83e9a2d"
                    datetime: "1970-01-01T12:00:00.000Z"
                    cadip:channel: 1
                    cadip:session_id: "S1A_20200105072204051313"
                    cadip:block_number: 2
                  stac_version: "1.0.0"
                  stac_extensions:
                    - "https://stac-extensions.github.io/file/v2.1.0/schema.json"
                    - "https://stac-extensions.github.io/alternate-assets/v1.1.0/schema.json"
