= Data retrieval

This module is responsible for external data retrieval.
It provides two main functionalities :

* search for data in a distant site with filter criteria
* download data from a distant site to local folder or a S3 bucket

It also handles authentication on these sites.

NOTE: TODO insert the class diagram class.mmd here

A DataRetriever is the main object of this module.
It handles the retrieval of external data.
It uses a Provider to interact with external data provider (search and download).
It uses a Storage to store downloaded data.
It uses a DownloadStatus to track download progress.

The DataRetriever handles all the business logic.
The technical aspects are handled by Provider, Storage and DownloadStatus.

== Search for data

NOTE: TODO insert the activity diagram 'search-activity.mmd' here

A DataProvider can search for data with criteria using the search function.
The Criteria is time period with a start date and an end date.

First, the DataProvider ensures its Provider is authenticated.
If not, it tries to log in.
In case of connexion issues, it raises a specific ConnexionFailed exception.
In case of authentication issues, it raises a specific AuthenticationFailed exception.

Then, the site asks its Provider to perform the search.
In case of error during search, it raises a specific SearchFailed exception.

Finally, it returns an iterable through the found data.
The found Data are product metadata properties (dict-like object).

== Download a data

NOTE: TODO insert the activity diagram 'download-activity.mmd' here

A site can download a file to a specific path from its external id using the download function.

First, the site ensures its Provider is authenticated.
If not, it tries to log in.
In case of connexion issues, it raises a specific ConnexionFailed exception.
In case of authentication issues, it raises a specific AuthenticationFailed exception.

Then, it updates the download status to indicate the download has started.

Then, the site asks its Provider to perform the download.
In case of error during download,
it updates the status with the error information,
and it raises a specific DownloadFailed exception.

Then, it asks its Storage to store the downloaded data with its Storage.

== Provider

The Provider is responsible for technical exchange with the external sites.
It is implemented with https://eodag.readthedocs.io/en/stable/index.html[EODAG] via the EodagProvider.

== Storage

The Storage is responsible for storing the file.
The main storage is the S3Bucket.

// TODO What techno to do the S3 interface ?

== Download status

The DownloadStatus is responsible for tracking download progress.
The status is stored in a postgresql database.
The interaction with this database are handled by the PGDownloadStatus.

// TODO fill when doing the story
