= Generate rs-server documentation

== Introduction

The rs-server documentation is mainly written using asciidoctor.
Nevertheless, the python api and the rest api are handled differently.
The python api is built using sphinx functionalities.
The rest api is built using fastapi and swagger functionalities.

Therefore, the built procedure includes specific steps to handle these elements.
The main documentation has reference to these elements for integration.

== Procedure

This procedure is run automatically in the CI by the 'generate documentation' workflow.
It can be executed locally to verify the generated documentation (before publishing it for example).

. Pre-requises

The local developer environment has been setup.

. Generate the python api documentation

Generate the rst files of the python api of the rs-server :
[source, bash]
----
poetry run sphinx-apidoc -o docs/api/python/generated rs_server
----

Generate the hmtl python api of the rs-server.
[source, bash]
----
poetry run sphinx-build -M html docs/api/python/ dist/doc/api
----

The generated api is accessible locally at 'dist/doc/api/html/index.html'.

. Generate the rest api documentation

NOTE: To be defined. This procedure will use native FastAPI functionalities.

. Generate the technical documentation

TODO add the procedure to generate asciidoctor documentation.

. Verify the documentation

The main page of the technical documentation is accessible locally at 'TODO'.
You can verify the generated documentation before publish it.

Important elements to check :

* the python api is accessible in the technical documentation
* the python api is well formatted
* the rest api is accessible in the technical documentation
* the rest api is well formatted
* ...
