# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[tool.poetry]
name = "rs-osam"
version = "0.0.0"
description = "Copernicus Sentinel OSAM (Object Storage Access Manager)."
license = "Apache-2.0"
authors = ["ESA under contract with Airbus and CS <ops_coprs@airbus.com>"]
readme = "README.md"
keywords = ["copernicus", "sentinel", "processing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: FastAPI",
    "Framework :: OpenTelemetry",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Image Processing"
]

packages = [

    { include = "osam"},
    # TODO add tests
    # { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.13,<4"
rs-server-common = "*" # then run 'poetry run opentelemetry-bootstrap -a install'
jsonpatch = "^1.33"
openapi-core = ">=0.22.0"
ovh = "^1.2.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
# rs-server-common = { git = "https://github.com/RS-PYTHON/rs-server.git", branch = "develop", subdirectory = "services/common" }
# rs-server-common = { git = "https://github.com/RS-PYTHON/rs-server.git", branch = "feat-rspyXXX/my-branch", subdirectory = "services/common" } # specific branch, for testing
rs-server-common = { git = "https://github.com/RS-PYTHON/rs-server.git", branch = "feat-rspy788/osam-api-key", subdirectory = "services/common" } # specific branch, for testing
# rs-server-common = {path = "../../rs-server/services/common", develop = true} # local rs-server-common, for testing
pre-commit = ">=3.7.1,<5.0.0"
pylint = "^4.0.2"
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"
pytest-cov = "^7.0.0"
pytest-docker = "^3.2.3"
pytest-error-for-skips = "^2.0.2"
pytest-mock = "^3.15.1"
pytest-httpx = ">=0.35,<0.36"
responses = "^0.25.3"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
metadata = false

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"


[tool.black]
line-length = 120

[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]
asyncio_mode = "auto"

[tool.mypy]
warn_redundant_casts = true
# Force analyze of partially annotate function signatures
check_untyped_defs = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 120
# per-file-ignores = [
#     '__init__.py:F401',
# ]

[tool.pylint]
max-line-length = 120
disable = [
    "logging-fstring-interpolation",  # Logging f-string interpolation
    "R0917",  # Too many positional arguments
    "E0401", # import-error
    "R0902", # too-many-instance-attributes
    "R0913"  # too-many-arguments
]
ignore-paths = '^docs/.*$'

# Only add notes as comments that are not checked for errors.
notes = ["XXX"]  # No errors on TODO and FIXME

min-similarity-lines = 10  # Minimum lines number of a similarity

[tool.bandit.assert_used]
skips = ['*/*.py']

[tool.bandit]
skips = ['B603', 'B607', 'B404']
