[project]
name = "rs-server-catalog"
version = "0.0.0" # see: https://github.com/mtkennerly/poetry-dynamic-versioning

[tool.poetry]
name = "rs-server-catalog"
version = "0.0.0"
description = "rs-server stac catalog"
authors = ["Your Name <you@example.com>"]

packages = [
    { include = "rs_server_catalog" },
    { include = "tests", format = "sdist" },
]


[tool.poetry.dependencies]
python = "^3.11"
# Common elements for all the rs-server services
rs-server-common = {path = "../common", develop = true}
stac-fastapi-pgstac = "^2.4.11"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-docker = "^3.1.0"
python-dotenv = "^1.0.1"
# httpx is used by fastapi for test purpose
httpx = "^0.26.0"
sqlalchemy-utils = "^0.41.1"
black = "^23.11.0"


[tool.black]
line-length = 120


[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]


[tool.poetry-dynamic-versioning] # needs: poetry self add "poetry-dynamic-versioning[plugin]"
enable = true
tagged-metadata = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
