[project]
name = "rs-server-catalog"
version = "0.0.0" # see: https://github.com/mtkennerly/poetry-dynamic-versioning

[tool.poetry]
name = "rs-server-catalog"
version = "0.0.0"
description = "rs-server stac catalog"
authors = ["Your Name <you@example.com>"]

packages = [
    { include = "rs_server_catalog" },
    { include = "rs_server_common" },
    { include = "tests", format = "sdist" },
]


[tool.poetry.dependencies]
python = "^3.11"
stac-fastapi-pgstac = "^2.4.11"
uvicorn = "^0.27.1"
moto = "==4.2.8"
flask = "^3.0.2"
flask-cors = "^4.0.0"
pytest-mock = "^3.12.0"
pygeofilter = "^0.2.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
# Formatting
black = "^23.11.0"
# Testing
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-error-for-skips = "^2.0.2"
pytest-docker = "^3.1.0"
pytest-dotenv = "^0.5.2"
# httpx is used by fastapi for test purpose
httpx = "^0.26.0"
# sqlalchemy-utils is used for pgstac test purpose
sqlalchemy-utils = "^0.41.1"
psycopg2 = "^2.9.9"


[tool.black]
line-length = 120


[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]
# pgstac and stac-fastapi env file for test purpose
env_files = [
    "tests/.env"
]


[tool.poetry-dynamic-versioning] # needs: poetry self add "poetry-dynamic-versioning[plugin]"
enable = true
tagged-metadata = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
