# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "rs-server-catalog"
dynamic = ["version"] # see: https://github.com/mtkennerly/poetry-dynamic-versioning

[tool.poetry]
name = "rs-server-catalog"
version = "0.0.0"
description = "Copernicus Sentinel rs-server, STAC catalog."
license = "Apache-2.0"
authors = ["ESA under contract with Airbus and CS <ops_coprs@airbus.com>"]
readme = "README.md"
homepage = "https://home.rs-python.eu/"
repository = "https://github.com/RS-PYTHON/rs-server"
documentation = "https://home.rs-python.eu/rs-documentation/rs-server/docs/doc/"
keywords = ["stac", "copernicus", "sentinel", "processing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: FastAPI",
    "Framework :: OpenTelemetry",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Image Processing"
]

packages = [
    { include = "rs_server_catalog" },
    { include = "tests", format = "sdist" },
]

# Add configuration files to the .whl package
include = [
    { path = "config", format = ["wheel"] }
]

[tool.poetry.dependencies]
python = ">=3.13,<4"
rs-server-common = "*"
# pypgstac cannot be update to 0.9.11 / 0.9.12 because of restrictive upper bound on cachetools
# see https://github.com/stac-utils/pgstac/pull/421
# but now pypgstac is deprecated, see https://github.com/stac-utils/pgstac/blob/main/docs/src/pypgstac.md
# it should be replaced by https://pypi.org/project/pypgstac-rs which does not exist yet as of 2026-08-06
pypgstac = {extras = ["psycopg"], version = "^0.9.10"}
xmltodict = "^1.0.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
rs-server-common = {path = "../common", develop = true}
# Formatting
black = ">=26.3.1"
# Testing
pytest = "^9.0.3"
pytest-asyncio = "^1.3.0"
pytest-cov = "^7.1.0"
pytest-docker = "^3.2.5"
pytest-dotenv = "^0.5.2"
pytest-error-for-skips = "^2.0.2"
pytest-httpx = ">=0.36"
pytest-mock = "^3.15.1"
pytest-responses = ">=0.5.1,<0.7.0"
moto = "^5.1.10"
flask = "^3.1.1" # for moto
flask-cors = "^6.0.1" # for moto
sqlalchemy-utils = "^0.42.0"
psycopg2 = "^2.9.11"


[tool.black]
line-length = 120


[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]
# pgstac and stac-fastapi env file for test purpose
env_files = [
    "tests/resources/db/.env"
]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"


[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
metadata = false

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
