classDiagram

    class LibraryModule {
    }

    class Service1EventWriter {
        on_search(with_param)
        on_download(with_param)
    }
    Service1EventWriter --> LibraryModule

    class Service1EventReader {
        search(with_param)
        download(with_param)
    }
    Service1EventReader ..> Service1EventWriter: kafka topic


    class Service1Endpoint {
        search(with_param)
        download(with_param)
    }

    class Service1ClusterEndpoint {
        search(with_param)
        download(with_param)
    }
    Service1Endpoint <| -- Service1ClusterEndpoint
    Service1ClusterEndpoint --> Service1EventReader

    class Service1LaptopEndpoint {
        search(with_param)
        download(with_param)
    }
    Service1Endpoint <| -- Service1LaptopEndpoint
    Service1LaptopEndpoint --> LibraryModule
