stations: |
  pedc:
    service:
      name: edrs
      url: http://mockup-station-pedc.processing.svc.cluster.local:8080
    domain: mockup-station-pedc.processing.svc.cluster.local
    authentication:
      auth_type: ftpes
      username: test
      password: test
      ca_crt: /certs/ca.crt
      client_crt: /certs/client.crt
      client_key: /certs/client.key

  bedc:
    service:
      name: edrs
      url: {URL}
      port: {PORT}
    domain: mockup-station-pedc.processing.svc.cluster.local
    authentication:
      auth_type: ftpes
      username: {USER}
      password: {PASS}
      ca_crt: /path/to/ca.crt
      client_crt: /path/to/client.crt
      client_key: /path/to/client.key
