site_name: RSPY

nav:
  - Home: index.md
  - CADIP: cadip.md
  - ADGS: adgs.md
  - Catalog: catalog.md
  - Frontend: frontend.md
  - Common: common.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_modules: true

theme:
  name: material
