name: build-technical-doc
description: "Build the technical documentation using asciidoxy"

runs:
  using: "composite"
  steps:
    # The technical documentation uses a dedicated python project to be built
    - uses: ./.github/actions/poetry-install
      with:
        working-directory: ./docs

    - name: Install asciidoctor
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoctor
      shell: bash

    - name: Generate technical documentation
      run: |
        poetry run asciidoxy --base-dir doc --build-dir ../dist/doc/ --multipage doc/index.adoc
      working-directory: ./docs
      shell: bash
