#!/usr/bin/env bash
# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# quay.io/jupyter/base-notebook:<tag>
ARG BASE=xxx
FROM ${BASE}

ARG DASK_TAG=xxx
ARG DASK_GATEWAY_TAG=xxx
ARG PREFECT_TAG=xxx
ARG PREFECT_DASK_TAG=xxx

USER root
RUN apt update && apt upgrade -y
USER jovyan

# Upgrade pip version
RUN pip install -U pip

# Additional python kernel to install to run the notebooks
ARG PYTHON_VERSION=3.11.7
ARG KERNEL_NAME=py3.11.7

# Install additional python kernel
USER root
RUN conda create -y -n "$KERNEL_NAME" python="$PYTHON_VERSION"
RUN source activate "$KERNEL_NAME" && \
    python -V && \
    pip install -U pip && \
    pip install ipykernel && \
    python -m ipykernel install --name "$KERNEL_NAME" --display-name "Python ($PYTHON_VERSION)"
# Set default kernel... does not seem to work
RUN jupyter notebook --generate-config
RUN echo "c.MappingKernelManager.default_kernel_name='$KERNEL_NAME'" >> /home/jovyan/.jupyter/jupyter_notebook_config.py
USER jovyan

# Note: put s3fs before boto3 to have a recent version
RUN source activate "$KERNEL_NAME" && pip install \
    dask[complete]=="${DASK_TAG}" \
    distributed=="${DASK_TAG}" \
    dask-gateway=="${DASK_GATEWAY_TAG}" \
    prefect[aws]=="${PREFECT_TAG}" \
    prefect-dask=="${PREFECT_DASK_TAG}" \
    ipywidgets \
    s3fs \
    boto3

# Install dot and clean conda
USER root
RUN apt install -y python3-pydot graphviz
RUN conda clean --all --yes
USER jovyan

# Note: don't remove cache so the child images that use this one as a base will build faster
# RUN rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-server"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/quay.io/jupyter/base-notebook:hub-5.2.1"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-server/blob/develop/resources/build_base_images/Dockerfile.jupyter.k8s"
