#!/usr/bin/env bash
# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# quay.io/jupyter/base-notebook:hub-<tag>
ARG BASE=xxx
FROM ${BASE}
ARG BASE=xxx

ENV PATH=/home/jovyan/.local/bin:${PATH}

ARG PYTHON_VERSION=3.13.9
ARG DASK_TAG=2024.5.2
ARG DASK_GATEWAY_TAG=2024.1.0
ARG PREFECT_TAG=3.2.13
ARG PREFECT_DASK_TAG=0.3.3

USER root

COPY ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh
RUN apt update && apt upgrade -y && pip install -U pip && layer-cleanup.sh

# Install python version and dependencies
RUN conda update -n base -c conda-forge conda && \
    conda install --yes conda-forge::python=${PYTHON_VERSION} && \
    python -V && \
    pip install -U pip && \
    pip install \
        dask[complete]=="${DASK_TAG}" \
        distributed=="${DASK_TAG}" \
        dask-gateway=="${DASK_GATEWAY_TAG}" \
        prefect[aws]=="${PREFECT_TAG}" \
        prefect-dask=="${PREFECT_DASK_TAG}" \
        ipywidgets \
        s3fs \
        boto3 && \
    conda clean --all --yes && \
    layer-cleanup.sh

# Install packages
RUN restore-apt.sh && apt update && apt install -y python3-pydot graphviz && layer-cleanup.sh

RUN chown -R jovyan /home/jovyan
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

USER jovyan

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-server"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/${BASE}"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-server/blob/develop/resources/build_base_images/Dockerfile.jupyter"
