# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: set-binary-env
description: Set environment for publishing binaries (wheels and Docker images)

inputs:
  wheel_version_name:
    description: Wheel version name, calculated from the git commit id, e.g. x.y.postz.dev0
    required: true
  manual_tag:
    description: User-defined tag from a manual trigger
    required: false

outputs:
  branch_name:
    description: Current branch name (or source branch for a pull request)
    value: ${{ steps.set-env.outputs.branch_name }}
  docker_tags:
    description: Docker tags to set to new images
    value: ${{ steps.set-env.outputs.docker_tags }}
  docker_temp_tag:
    description: Temp Docker tag to set to new images (real tags will be set after the tests are passed)
    value: ${{ steps.set-env.outputs.docker_temp_tag }}

runs:
  using: "composite"
  steps:
      - id: set-env
        run: |
          set -x

          # Get the current branch name (or source branch for a pull request)
          if [[ ${{ github.event_name }} == pull_request ]]; then
            branch_name="${{ github.event.pull_request.head.ref }}"
          else
            branch_name="${{ github.ref_name }}"
          fi

          # The first docker tag is the wheel version name
          docker_tags="${{ inputs.wheel_version_name }}"

          # Calculate the second docker tag.
          # For a pull request, use the branch name
          if [[ ${{ github.event_name }} == pull_request ]]; then
            docker_tags="${docker_tags},${branch_name}"

          # For a push on develop or a tag, use the docker tag :latest
          elif [[ ${{ github.event_name }} == push ]]; then
            docker_tags="${docker_tags},latest"

          # For a manual trigger, use the user-defined tag
          elif [[ ${{ github.event_name }} == workflow_dispatch ]]; then
            docker_tags="${docker_tags},${{ inputs.manual_tag }}"

          else
            >&2 echo "Unknown trigger"
            exit 1
          fi

          # The 'latest' image tag is sensitive, so we want to push it only after the tests have passed.
          # In the meantime, we'll use a temporary unique docker tag = the ci/cd workflow run id.
          [[ ",${docker_tags}," =~ ",latest," ]] && docker_temp_tag="run-${{github.run_id}}"

          # Save values
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          echo "docker_tags=$docker_tags" >> $GITHUB_OUTPUT
          echo "docker_temp_tag=$docker_temp_tag" >> $GITHUB_OUTPUT
        shell: bash
