' Copyright 2023-2026 Airbus, CS Group
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml dask-eopf-logging-prefect

actor John
activate Prefect_UI

John -> Prefect_UI: Run processing-flow
Prefect_UI -> Prefect_Runner ++ : Start processing flow
Prefect_Runner -> Prefect_Runner++ : Generate payload
Prefect_Runner -> RS_DPR_Service++ : POST /processes/{processID}/execution
RS_DPR_Service -> Dask_Worker++ : dask_client.submit()
Dask_Worker -> eopf++: subprocess.run()
eopf --> Dask_Worker: stdout (log / print)
Dask_Worker --> RS_DPR_Service: dask_client.print()\nand/or\ndask_client.forward_logging()
Prefect_Runner -> RS_DPR_Service: GET /jobs/{job_id}/logs
RS_DPR_Service --> Prefect_Runner: logs stream (text/event-stream)
Prefect_Runner --> Prefect_UI: Prefect Run logs

@enduml
