' Copyright 2023-2026 Airbus, CS Group
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml edrs-stac

actor John
collections RS_Server_EDRS
activate RS_Server_EDRS

note over John, RS_Server_EDRS: John has access to 2 EDRS centers: pedc and bedc

John -> RS_Server_EDRS: GET /edrs
RS_Server_EDRS --> John: STAC landing page

John -> RS_Server_EDRS: GET /edrs/collections
RS_Server_EDRS --> John: {s1_pedc, s1_bedc, s2_pedc, s2_bedc}

newpage EDRS items

John -> RS_Server_EDRS: GET /edrs/collections/s1_pedc/items
RS_Server_EDRS -> EDRS_pedc ++ : AUTH TLS
EDRS_pedc --> RS_Server_EDRS : 234 AUTH TLS successful
RS_Server_EDRS -> EDRS_pedc : USER
EDRS_pedc --> RS_Server_EDRS : 331 Need Password
RS_Server_EDRS -> EDRS_pedc : PASS
EDRS_pedc --> RS_Server_EDRS : 230 Authorized
RS_Server_EDRS -> EDRS_pedc : MLSD NOMINAL/S1A
EDRS_pedc --> RS_Server_EDRS : <mlsd sessions response/>
loop over S1A sessions
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S1A/DCS_<nn>_<SessionID>_dat/ch_1
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_1 files response/>
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S1A/DCS_<nn>_<SessionID>_dat/ch_2
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_2 files response/>
end
RS_Server_EDRS -> EDRS_pedc : MLSD NOMINAL/S1C
EDRS_pedc --> RS_Server_EDRS : <mlsd sessions response/>
loop over S1C sessions
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S1C/DCS_<nn>_<SessionID>_dat/ch_1
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_1 files response/>
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S1C/DCS_<nn>_<SessionID>_dat/ch_2
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_2 files response/>
end
RS_Server_EDRS -> RS_Server_EDRS : FTP > STAC mapping
RS_Server_EDRS --> John : {STAC response}

John -> RS_Server_EDRS: GET /edrs/collections/s2_pedc/items
RS_Server_EDRS -> EDRS_pedc ++ : AUTH TLS
EDRS_pedc --> RS_Server_EDRS : 234 AUTH TLS successful
RS_Server_EDRS -> EDRS_pedc : USER
EDRS_pedc --> RS_Server_EDRS : 331 Need Password
RS_Server_EDRS -> EDRS_pedc : PASS
EDRS_pedc --> RS_Server_EDRS : 230 Authorized
RS_Server_EDRS -> EDRS_pedc : MLSD NOMINAL/S2A
EDRS_pedc --> RS_Server_EDRS : <mlsd sessions response/>
loop over S2A sessions
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S2A/DCS_<nn>_<SessionID>_dat/ch_1
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_1 files response/>
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S2A/DCS_<nn>_<SessionID>_dat/ch_2
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_2 files response/>
end
RS_Server_EDRS -> EDRS_pedc : MLSD NOMINAL/S2B
EDRS_pedc --> RS_Server_EDRS : <mlsd sessions response/>
loop over S2B sessions
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S2B/DCS_<nn>_<SessionID>_dat/ch_1
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_1 files response/>
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S2B/DCS_<nn>_<SessionID>_dat/ch_2
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_2 files response/>
end
RS_Server_EDRS -> EDRS_pedc : MLSD NOMINAL/S2C
EDRS_pedc --> RS_Server_EDRS : <mlsd sessions response/>
loop over S2C sessions
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S2C/DCS_<nn>_<SessionID>_dat/ch_1
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_1 files response/>
RS_Server_EDRS -> EDRS_pedc  : MLSD NOMINAL/S2C/DCS_<nn>_<SessionID>_dat/ch_2
EDRS_pedc --> RS_Server_EDRS : <mlsd ch_2 files response/>
end
RS_Server_EDRS -> RS_Server_EDRS : FTP > STAC mapping
RS_Server_EDRS --> John : {STAC response}

newpage EDRS queryables

John -> RS_Server_EDRS: GET /cadip/queryables
RS_Server_EDRS --> John: {platform}

@enduml
