' Copyright 2023-2026 Airbus, CS Group
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml python-components

node "RS Server" {
  component [rs.server]
}

node "RS Client Libraries" {
  package "rs.common" {
    [rs.common.log]
    [rs.common.trace]
    [rs.common.metrics]
  }

  component [rs.client]
  component [rs.processing]

  package "rs.chain" {
    [rs.chain.on_demand]
    [rs.chain.systematic]
    [rs.chain.operations]
  }
}

[rs.server] --> [rs.common.log]
[rs.server] --> [rs.common.trace]
[rs.server] --> [rs.common.metrics]

[rs.client] --> [rs.common.log]
[rs.client] --> [rs.common.trace]
[rs.client] --> [rs.common.metrics]

[rs.processing] --> [rs.common.log]
[rs.processing] --> [rs.common.trace]
[rs.processing] --> [rs.common.metrics]

[rs.chain.on_demand] --> [rs.client]
[rs.chain.on_demand] --> [rs.processing]

[rs.chain.systematic] --> [rs.client]
[rs.chain.systematic] --> [rs.processing]

[rs.chain.operations] --> [rs.client]

@enduml
