# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

info:
  description: |
    The Copernicus Space Component Reference System is an open-source software solution allowing to implement,
    maintain, deploy, operate and monitor Sentinel data processing workflows based on the future re-engineered Level
    0, 1, 2 Sentinel Data processors (Q3 2024/2025).

    <a href="https://home.rs-python.eu/">Website</a>

    <a href="https://home.rs-python.eu/rs-documentation/">Documentation</a>

    <a href="${RSPY_UAC_HOMEPAGE}">API-Key Manager</a>
services:
  adgs:
    openapi_url: http://localhost:8001/openapi.json
  cadip:
    openapi_url: http://localhost:8002/openapi.json
  staging:
    openapi_url: http://localhost:8100/openapi.json
  catalog:
    openapi_url: http://localhost:8003/api
    change_tags:
      "": Catalog
      Liveliness/Readiness: Catalog (Liveliness/Readiness)
      Transaction Extension: Catalog (Transaction Extension)
      Filter Extension: Catalog (Filter Extension)
      Bulk Transaction Extension: Catalog (Bulk Transaction Extension)
