name: poetry-install
description: "'poetry install' this project and dependencies"

inputs:
  options:
    description: "'poetry install' options e.g. '--with dev'"
    required: false
    default: --with dev

  working-directory:
    description: "the working directory in which poetry is run."
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-python
    - uses: snok/install-poetry@v1
    - run: |
        poetry install ${{ inputs.options }} # don't use quotes around options
        poetry run opentelemetry-bootstrap -a install || true # install otel instrumentation packages for dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
