name: build-rest-api
description: "Build REST API reference guide using FastAPI and SwaggerUI."

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/poetry-install

    - name: Copy root file for REST API
      run: |
        mkdir -p dist/doc/output/api/rest/
        cp docs/doc/api/rest/index.html dist/doc/output/api/rest/
      shell: bash

    - name: Generate openapi specification
      run: |
        poetry run python -m tests.openapi dist/doc/output/api/rest/
      shell: bash
