# Copyright 2023-2025 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This Dockerfiles installs rs-server-staging in the dask-gateway image for local and cluster modes.
# Target Docker image name:
# ghcr.io/rs-python/dask/staging
#

ARG BASE_IMAGE_TARGET=xxx

# Versions used: currently staging use Dask 2026.1.2 with Python 3.13.11, and the base images are all built with dask-gateway 2025.4.0
# Base images for local mode also include dask-gateway-server with the same version as dask-gateway
# ANY VERSION CHANGE MUST BE UPDATED IN THE BASE IMAGES SCRIPT GENERATOR (docker/base/build-base-images.sh) AND IN THIS FILE.
ARG PYTHON_VERSION=3.13.11
ARG DASK_TAG_STAGING=2026.1.2

FROM ghcr.io/rs-python/dask/dask-gateway:${BASE_IMAGE_TARGET}-py${PYTHON_VERSION}-${DASK_TAG}

# Default user from parent image
ARG USER=dask:dask

# Install dependencies for compilation
USER root

COPY ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

RUN restore-apt.sh && apt update && apt upgrade -y && apt install -y libpq-dev gcc git && layer-cleanup.sh
USER $USER

# The CI builds the wheel packages, downloads them into ./whl/, then builds this Dockerfile from ./whl/,
# so the .whl files are under ./*.whl
# We copy them into a /tmp directory that we can clean at the end.
RUN mkdir -p /tmp/whl
ADD ./*.whl /tmp/whl

# Install the wheel packages in the right order (dependencies first).
# This also installs all the sub-dependencies e.g. fastapi etc ...
# https://home.rs-python.eu/local-pypi is used for additional dependencies, see: https://github.com/RS-PYTHON/local-pypi
RUN cd /tmp/whl && pip install -U --no-cache-dir \
    --extra-index-url=https://home.rs-python.eu/local-pypi/ \
    rs_server_common-*.whl rs_server_staging-*.whl && \
    layer-cleanup.sh

# Install opentelemetry instrumentation packages for dependencies
RUN opentelemetry-bootstrap -a install && layer-cleanup.sh

# Remove dependencies for compilation
USER root
RUN apt autoremove -y gcc git && layer-cleanup.sh

# Install dependencies necessary for execution not compilation
RUN restore-apt.sh && apt update && apt install -y libexpat1 && layer-cleanup.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

USER $USER

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-server"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-server/blob/develop/services/staging/.github/Dockerfile.dask-staging"
