# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check code quality

on:
  push:
    branches:
      - develop # pushes on the 'develop' branch
    tags:
      - '**' # new git tags (including hierarchical tags like v1.0/beta)
  pull_request:
    types: [opened, synchronize, reopened]
    # run this worflow only for code/test related changes (avoid it for documentation)
    paths: ['**.json', '**.lock', '**.py', '**.raw', '**.sh', '**.toml', '**.yaml', '**.yml']
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.13.12

jobs:

  # Ugly workaround for: https://github.com/actions/runner/issues/2372
  setup:
    runs-on: ubuntu-latest
    outputs:
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
    steps:
       - run: echo "All set!"

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
      conf: ${{ steps.filter.outputs.conf }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            code: ['**/*[dD]ockerfile*', '**.toml', '**.py', '**.yaml', '**.yml']
            conf: ['**.lock', '**.json', '**.raw']

  check-format:
    runs-on: ubuntu-latest
    name: Check format (pre-commit, black, isort)
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install-python
      - run: >
          echo
          ":information_source: This job checks that you have run \`pre-commit run --all-files\` in
          your local git repository before committing."
          >> $GITHUB_STEP_SUMMARY
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  check-license:
    runs-on: ubuntu-latest
    name: Check copyright license headers
    needs: changes
    permissions:
      contents: write
      pull-requests: write
    if: ${{ needs.changes.outputs.code == 'true' }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: check License Header
        uses: apache/skywalking-eyes/header@8c96ee223558797cdd9eba82c0919258e1cf2dad # main
        with:
          log: debug
          mode: check

  check-linting:
    runs-on: ubuntu-latest
    name: Check linting (pylint, flake8)
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/poetry-install
        with:
          rm-plugin-dir: true

      - name: Run pylint
        if: always() # even if previous steps returned a non-zero exit code
        run: |
          set -x
          poetry run pylint "**/*.py" --output-format=colorized,parseable:./pylint-report.txt

      - name: Run flake8
        if: always()
        run: |
          set -x
          poetry run flake8 . || true # run next line even if fails
          poetry run flake8 . --output-file ./flake8-report.txt

      - name: Save reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: check-linting
          path: |
            ./flake8-report.txt
            ./pylint-report.txt
          retention-days: 1

  check-typing:
    runs-on: ubuntu-latest
    name: Check typing (mypy)
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/poetry-install
        with:
          rm-plugin-dir: true
      - name: Run mypy
        run: poetry run mypy --install-types --non-interactive --explicit-package-bases .
        shell: bash

  check-security:
    runs-on: ubuntu-latest
    name: Check security (bandit, safety, trivy)
    permissions:
      security-events: write # needed for github/codeql-action/upload-sarif
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/poetry-install
        with:
          rm-plugin-dir: true

      - id: bandit
        name: Run bandit
        if: always() # even if previous steps returned a non-zero exit code
        run: |
          set -x
          poetry run bandit -c pyproject.toml -r . || true # run next line even if fails
          poetry run bandit -c pyproject.toml -r . -f json -o ./bandit-report.json
        shell: bash

      - id: safety
        name: Run safety
        if: always() && github.actor != 'dependabot[bot]' # dependabot does not have access to secrets
        env:
            SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: |
          set -x
          poetry run safety --key $SAFETY_API_KEY scan --detailed-output
        shell: bash

      - name: Run Trivy vulnerability scanner
        if: always()
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          version: v0.69.3
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-results-fs.sarif
          exit-code: 1
          #severity: 'CRITICAL'

      - name: Save reports as artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: check-security
          path: |
            ./bandit-report.json
            ./trivy-results-fs.sarif
          retention-days: 1

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results-fs.sarif
          category: git repository

      - name: "Display link to Trivy results"
        if: always()
        run: |

          set -x

          # If this is not a pull request, the query is "is:open+branch:branch_name"
          if [[ "${{ github.ref_name }}" != *merge* ]]; then
            query="is:open+branch:${{ github.ref_name }}"

          # Else the ref_name is e.g. '13/merge'. Change it into 'pr:13'
          else
            query=$(sed "s|\(.*\)/merge|pr:\1|g" <<< "${{ github.ref_name }}")
          fi

          echo "Trivy scan results:" \
          "https://github.com/${{ github.repository }}/security/code-scanning?query=${query}" \
          >> $GITHUB_STEP_SUMMARY
        shell: bash

  run-all-pytests:
    runs-on: ubuntu-latest
    name: Run pytest # pytest unit and integration tests
    needs: [setup]

    # Only for this job: try to install and run different python versions.
    # All other jobs only use the env PYTHON_VERSION that is set above in this file.
    strategy:
      matrix:
        # python-version: ["${{ needs.setup.outputs.PYTHON_VERSION }}", 3.13t, 3.14, 3.15.0a2 ]
        python-version: ["${{ needs.setup.outputs.PYTHON_VERSION }}" ]
        include:
          - experimental: false
#          - python-version: 3.13t # free-threaded mode, with the global interpreter lock (GIL) disabled
#            experimental: true
#          - python-version: 3.14
#            experimental: true
#          - python-version: 3.15.0a2
#            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/poetry-install
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run pytest
        run: ./resources/all_pytests.sh --install
        shell: bash

      - name: Display code coverage summary in this console
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with: # see https://github.com/marketplace/actions/code-coverage-summary#inputs
          filename: ./cov-report.xml

      - name: Save reports
        uses: actions/upload-artifact@v7
        if: ${{ matrix.python-version == env.PYTHON_VERSION }}
        with:
          name: run-all-pytests
          path: |
            .coverage
            ./cov-report.xml
            ./junit-xml-report.xml
          retention-days: 1

  generate-quality-report:
    runs-on: ubuntu-latest
    name: Quality report (sonarqube)
    needs: [changes, check-linting, check-security, run-all-pytests] # see actions/download-artifact below
    if: ${{ needs.changes.outputs.code == 'true' }}
    permissions:
      pull-requests: write # for: phwt/sonarqube-quality-gate-action
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: RS-PYTHON_rs-server
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Full history for SCM and branch analysis
      - name: Download linting reports
        uses: actions/download-artifact@v8
        with:
          name:
            check-linting
      - name: Download vulnerability reports
        uses: actions/download-artifact@v8
        with:
          name:
            check-security
      - name: Download pytest reports
        uses: actions/download-artifact@v8
        with:
          name:
            run-all-pytests

      - name: Get directory names
        id: dir_names
        run: |
          echo tests=$(find . -type d -name "tests" | paste -sd ",") >> $GITHUB_OUTPUT
        shell: bash

      - name: Normalize coverage paths for SonarCloud
        run: |
          sed -i 's|<source>[^<]*</source>|<source>.</source>|g' ./cov-report.xml

      - name: Run SonarCloud Scanner
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7
        with:
          # See doc: https://docs.sonarsource.com/sonarqube-cloud
          #
          # "sonar.coverage.exclusions" excludes some files from the test coverage metrics but those files are still
          # analyzed: other metrics, duplications, coding rules...
          #
          # "sonar.exclusions" completely excludes some files from the analysis: those files don't appear at all
          # in SonarQube.
          #
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=rs-python
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.sources=.
            -Dsonar.tests=${{ steps.dir_names.outputs.tests }}
            -Dsonar.coverage.exclusions=tests,tests/**,**/tests/**,resources/sync_config_files.py
            -Dsonar.exclusions=tests,tests/**,**/tests/**,services/common/rs_server_common/footprint_facility.py
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.language=py
            -Dsonar.python.version=${{ env.PYTHON_VERSION }}
            -Dsonar.python.pylint.reportPaths=./pylint-report.txt
            -Dsonar.python.flake8.reportPaths=./flake8-report.txt
            -Dsonar.python.bandit.reportPaths=./bandit-report.json
            -Dsonar.python.coverage.reportPaths=./cov-report.xml
            -Dsonar.python.xunit.reportPath=./junit-xml-report.xml

      - name: Wait for quality gate result
        run: sleep 5

      - name: Report quality gate result in the pull request comment
        uses: phwt/sonarqube-quality-gate-action@e8842ff65b97bfa4fd4effe3ab0909f568d16e91 # v1
        id: quality-gate-result
        with:
          sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          sonar-token: ${{ env.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Output result
        run: |
          echo "Project status: ${{ steps.quality-gate-result.outputs.project-status }}"
          echo "Quality gate result: ${{ steps.quality-gate-result.outputs.quality-gate-result }}"

      - id: check-gate
        name: Check quality gate status
        uses: sonarsource/sonarqube-quality-gate-action@cb3ed20f9fec62b4c3b8ad9e77656c6adaade913 # master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
