name: Publish wheels and Docker images

# TODO: is it possible to run this workflow only if the check-code-quality workflow has completed successfully ?
# I've tried workflow_run but see:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
# Note: This event will only trigger a workflow run if the workflow file is on the default branch.

# Run workflow only for new git tags (including hierarchical tags like v1.0/beta), or manually
on:
  # push:
    # tags:
    #   - '**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

jobs:

  rs-server-whl:
    runs-on: ubuntu-latest
    name: "'rs-server' wheel"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-wheel

  services-common-whl:
    runs-on: ubuntu-latest
    name: "'services/common' wheel"
    outputs:
      package_name: ${{ steps.publish-wheel.outputs.package_name }}
    steps:
      - uses: actions/checkout@v4
      - id: publish-wheel
        uses: ./.github/actions/publish-wheel
        with:
          package_directory: services/common

  services-cadip-whl:
    runs-on: ubuntu-latest
    name: "'services/cadip' wheel"
    needs: [services-common-whl]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poetry-install

      - name: Download .whl dependencies
        uses: actions/download-artifact@v3
        with:
          name:
            ${{ needs.services-common-whl.outputs.package_name }}

      # Hack the pyproject.toml. TODO: find a cleaner to do this.
      - run: |
          set -x
          # Replace '<dep> = {path = "./relative/path", develop = true}' by '<dep> = "*"'.
          sed -i "s|^.*rs-server-common.*path.*$|rs-server-common = \"\*\"|g"  services/cadip/pyproject.toml

          # Update project with local whl installation of the dependencies
          #pip install ./rs_server_common-*.whl
          #poetry add rs-server-common
          #poetry install
          cd services/cadip && poetry build

      - uses: ./.github/actions/publish-wheel
        with:
          package_directory: services/cadip
