# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish wheels and Docker images

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
  workflow_dispatch: # manual trigger
    inputs:
      docker_tag:
        description: Add this tag to the docker images as e.g. 'latest' or 'feat-rspy123'
        required: false

env:
  PYTHON_VERSION: 3.13.12
  DOCKER_REGISTRY: ghcr.io

jobs:

  build-wheels:
    name: "Build wheels"
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    continue-on-error: false
    strategy:
      matrix:
        service: # all services must be under the services/ folder
          - adgs
          - cadip
          # - catalog
          # - common
          # - frontend
          # - osam
          # - prip
          # - staging
    outputs:
      version_name: ${{ steps.outputs.outputs.version_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # so that Dunamai produce the correct version

      - if: ${{ matrix.service == 'frontend' }}
        uses: ./.github/actions/install-python

      - if: ${{ matrix.service == 'frontend' }}
        name: Generate the aggregated openapi.json/swagger
        run: |
          set -x
          pip install poetry # we need poetry for the sub-projects, but no need to install the root project
          ./services/frontend/resources/build_aggregated_openapi.sh --run-services --set-version

      # - id: build-wheel
      #   uses: ./.github/actions/build-wheel
      #   with:
      #     package_directory: "services/${{ matrix.service }}"

      - id: build-wheel
        run: |
          set -x
          touch rs_server_${{ matrix.service }}-1.0a8.post72.dev0-py3-none-any.whl
          touch rs_server_${{ matrix.service }}-1.0a8.post72.dev0.tar.gz
          echo "version_name=1.0a8.post72.dev0" >> "$GITHUB_OUTPUT"
      - name: Save wheel package as artifact
        uses: actions/upload-artifact@v7
        with:
          name: rs_server_${{ matrix.service }}-1.0a8.post72.dev0-py3-none-any.whl
          path: rs_server_${{ matrix.service }}-1.0a8.post72.dev0-py3-none-any.whl
      - name: Save sdist as artifact
        uses: actions/upload-artifact@v7
        with:
          name: rs_server_${{ matrix.service }}-1.0a8.post72.dev0.tar.gz
          path: rs_server_${{ matrix.service }}-1.0a8.post72.dev0.tar.gz

      - id: outputs
        # The version name should be the same for all services. Save it only once for any service.
        if: ${{ matrix.service == 'adgs' }}
        run: echo "version_name=${{ steps.build-wheel.outputs.version_name }}" >> "$GITHUB_OUTPUT"

  set-env:
    name: Set environment
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    runs-on: ubuntu-latest
    needs: build-wheels
    outputs:
      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
      docker_tags: ${{ steps.set-binary-env.outputs.docker_tags }} # separated by ,
      docker_temp_tag: ${{ steps.set-binary-env.outputs.docker_temp_tag }}
      debug_mode: ${{ steps.other-env.outputs.debug_mode }}
    steps:
      - id: set-binary-env
        name: Call action 'set-binary-env'
        uses: RS-PYTHON/rs-server/.github/actions/set-binary-env@feat-rspy964/push-latest-after-tests
        with:
          wheel_version_name: ${{ needs.build-wheels.outputs.version_name }}
          manual_tag: ${{ github.event.inputs.docker_tag }}

      - id: other-env
        run: |
          set -x

          # Always use the debug mode except for new tags
          [[ "${{ github.ref_type }}" == tag ]] && debug_mode=false || debug_mode=true
          echo "debug_mode=$debug_mode" >> $GITHUB_OUTPUT

  publish-docker-images:
    name: "Build and publish Docker images"
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    needs: [set-env, build-wheels]
    permissions:
     security-events: write # needed for github/codeql-action/upload-sarif
     packages: write # needed for 'docker push'
    outputs:
      last_image_tag: ${{ steps.publish-docker.outputs.last_image_tag }} # same value for all images
    strategy:
      matrix:
        image:
          - adgs
          - cadip
          # - catalog
          # - frontend
          # - osam
          # - prip
          # - staging
          # - staging-dask-k8s
          # - staging-dask-local

        # Options specific to each image.
        # whl_pattern is a glob pattern to download the right binary wheels:
        # rs_server_adgs-<version>.whl, rs_server_cadip-<version>.whl, ...
        # Other options are from the publish-docker action.
        include:
          - image: adgs
            whl_pattern: "{rs_server_adgs-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/adgs/.github/Dockerfile
            image_suffix: rs-server-adgs
          - image: cadip
            whl_pattern: "{rs_server_cadip-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/cadip/.github/Dockerfile
            image_suffix: rs-server-cadip


            build_args: "REMOVE=ME"
          # - image: catalog
          #   whl_pattern: "{rs_server_catalog-*.whl,rs_server_common-*.whl}"
          #   dockerfile: ./services/catalog/.github/Dockerfile
          #   image_suffix: rs-server-catalog
          # - image: frontend
          #   whl_pattern: "rs_server_frontend-*.whl"
          #   dockerfile: ./services/frontend/.github/Dockerfile
          #   image_suffix: rs-server-frontend
          # - image: osam
          #   whl_pattern: "{rs_server_osam-*.whl,rs_server_common-*.whl}"
          #   dockerfile: ./services/osam/.github/Dockerfile
          #   image_suffix: rs-server-osam
          # - image: prip
          #   whl_pattern: "{rs_server_prip-*.whl,rs_server_common-*.whl}"
          #   dockerfile: ./services/prip/.github/Dockerfile
          #   image_suffix: rs-server-prip
          # - image: staging
          #   whl_pattern: "{rs_server_staging-*.whl,rs_server_common-*.whl}"
          #   dockerfile: ./services/staging/.github/Dockerfile
          #   image_suffix: rs-server-staging
          # - image: staging-dask-k8s
          #   whl_pattern: "{rs_server_staging-*.whl,rs_server_common-*.whl}"
          #   dockerfile: ./services/staging/.github/Dockerfile.dask-staging
          #   image_suffix: dask/staging/k8s
          #   build_args: "BASE_IMAGE_TARGET=k8s"
          # - image: staging-dask-local
          #   whl_pattern: "{rs_server_staging-*.whl,rs_server_common-*.whl}"
          #   dockerfile: ./services/staging/.github/Dockerfile.dask-staging
          #   image_suffix: dask/staging/local
          #   build_args: "BASE_IMAGE_TARGET=local"

    steps:
      - uses: actions/checkout@v6

      # Download .whl files into a local dir
      - name: Download .whl dependencies
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ matrix.whl_pattern }}
          path: ./build_context_path
          merge-multiple: true

      # Copy the entrypoint script under the same dir
      - if: ${{ matrix.image == 'frontend' }}
        name: Copy entrypoint script
        run: cp ./services/frontend/.github/entrypoint_frontend.sh ./build_context_path

      - name: Copy Dockerfile requirements
        run: cp -t ./build_context_path ./.github/scripts/layer-cleanup.sh ./.github/scripts/restore-apt.sh

      - name: Copy debug mode dependencies
        if: ${{ needs.set-env.outputs.debug_mode == 'true' }}
        run: cp -t ./build_context_path ./.github/scripts/git_debug_image.sh

      - run: ls ./build_context_path

      - id: publish-docker
        uses: ./.github/actions/publish-docker
        with:
          dockerfile: ${{ matrix.dockerfile }}
          build_context_path: ./build_context_path
          image_basename: ${{ github.repository_owner }}/
          image_suffix: ${{ matrix.image_suffix }}
          image_tags: ${{
            case(needs.set-env.outputs.docker_temp_tag != '',
            needs.set-env.outputs.docker_temp_tag,
            needs.set-env.outputs.docker_tags) }} # pass the temp tag if defined, else the nominal tags
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_args: ${{ matrix.build_args }}
          branch_name: ${{ needs.set-env.outputs.branch_name }}
          debug_mode: ${{ needs.set-env.outputs.debug_mode }}

      - uses: cloudposse/github-action-matrix-outputs-write@81ea135d4c4f90a5220bb38304380073c571dbb8
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.image }}
          outputs: |
            docker_images: ${{ steps.publish-docker.outputs.docker_images }}

  get-pushed-images:
    name: Get pushed Docker image names
    needs: [set-env, publish-docker-images]
    # Only if a temp Docker tag has been set
    if: ${{ (github.actor != 'dependabot[bot]') && (needs.set-env.outputs.docker_temp_tag != '' )}}
    runs-on: ubuntu-latest
    outputs:
      pushed_images: ${{ steps.read.outputs.pushed_images }}
    steps:
      - id: read-matrix-outputs
        uses: cloudposse/github-action-matrix-outputs-read@ddb62566e896c85614f5eeec2daa43d6d1dc6cb0
        with:
            matrix-step-name: publish-docker-images
      - id: read
        run: |
          set -x

          # Docker images that have been pushed
          # e.g. {"docker_images": {"cadip": "<cadip_image>", "adgs": "<adgs_image>" }}
          json_images='${{ steps.read-matrix-outputs.outputs.result }}' # use simple quotes, not double quotes !
          pushed_images=$(echo "$json_images" | jq -r .docker_images[] | paste -sd,) # separate values with ','

          echo pushed_images="$pushed_images" >> "$GITHUB_OUTPUT"

  # Test rs-demo with the new Docker images
  test-demo:
    name: Test rs-demo
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: [set-env, build-wheels, publish-docker-images, get-pushed-images]
    permissions:
     packages: write # needed for 'docker push'
    steps:
      - name: Log into Docker registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test rs-demo
        env:
          BRANCH_NAME: ${{ needs.set-env.outputs.branch_name }}
          DOCKER_TAG: ${{ needs.publish-docker-images.outputs.last_image_tag }}
        run: |
          set -x

          # Clone the rs-demo repository
          git clone https://github.com/RS-PYTHON/rs-demo.git
          cd rs-demo

          # Run the rs-demo local mode using the newly created docker images
          #./test-rs-demo.sh

      # If we used a temp docker tag, and only if the tests succeeded, then
      # we tag the images with the real tags and push them.
      - name: Tag and push Docker images
        if: ${{ needs.set-env.outputs.docker_temp_tag != '' }}
        uses: RS-PYTHON/rs-server/.github/actions/tag-push-docker@feat-rspy964/push-latest-after-tests
        with:
          old_docker_images: ${{ needs.get-pushed-images.outputs.pushed_images }}
          new_tags: ${{ needs.set-env.outputs.docker_tags }}

  publish-wheels-pypi:
    name: "Publish wheels and sdists to PyPI"
    if: (github.actor != 'dependabot[bot]') && (github.event_name == 'push') && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [test-demo] # only if the tests succeeded
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download dist dependencies
        uses: actions/download-artifact@v8
        with:
          path: ./dist
          merge-multiple: true
      - name: Publish wheel and sdist packages
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          skip-existing: true
          packages-dir: ./dist
          verbose: true
