# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish wheels and Docker images

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
  workflow_dispatch: # manual trigger
    inputs:
      docker_tag:
        description: Add this tag to the docker images as e.g. 'latest' or 'feat-rspy123'
        required: false

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-frontend:
    name: Build frontend openapi.json
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    permissions:
      contents: write # for the git push
    steps:
      - uses: actions/checkout@v6
        with:
          # Checkout branch not pr (needed by git push)
          ref: ${{ case(github.event_name == 'pull_request', github.head_ref, '') }}
          fetch-depth: 0 # to have file history
      - uses: actions/checkout@v6
        with:
          repository: RS-PYTHON/rs-dpr-service
          path: rs-dpr-service
          fetch-depth: 0
      - id: find
        name: Find all files that could modify openapi.json
        run: |
          set -x
          found=

          # Find all python files that contain something like @app.delete, @router.get, ...
          found="${found} $(grep --include="*.py" --exclude-dir="tests" -lrE "@.*\.(delete|get|patch|put|post)")"

          # Add project files that contain the pygeoapi or stac-fastapi version
          found="${found} \
            services/catalog/poetry.lock \
            services/staging/poetry.lock \
            services/common/poetry.lock \
            rs-dpr-service/poetry.lock"

          # Add everything from the frontend, except the openapi.json file itself
          found="${found} \
            $(find \
                services/frontend/rs_server_frontend \
                services/frontend/resources \
                services/frontend/tools \
                -type f -not -path "**/openapi.json")"

          # If I forgot some files, add them here with: found="${found} path/to/file1 path/to/file2"
          # Or simply run this command locally:
          # ./services/frontend/resources/build_aggregated_openapi.sh --run-services --set-version
          # and commit/push the result to your branch.

          # We'll generate, commit and push this file only if its last commit is older than
          # or equal to any of the above files
          generated="services/frontend/resources/openapi.json"
          last_generation=$(TZ=GMT git log -1 --format=%cd --date=iso-local $generated)

          regenerate=false
          for file in $found; do
            # Change directory, needed for rs-dpr-service
            file_change=$(cd $(dirname $file) && TZ=GMT git log -1 --format=%cd --date=iso-local $(basename $file))
            if [[ ("$last_generation" < "$file_change") || ("$last_generation" == "$file_change") ]]; then
              regenerate=true
              break
            fi
          done
          echo "regenerate=$regenerate" >> "$GITHUB_OUTPUT"

      - if: ${{ steps.find.outputs.regenerate == 'true'}}
        uses: RS-PYTHON/actions/.github/actions/setup-poetry@feat-rspy964/push-latest-after-tests
      - name: Generate the aggregated openapi.json/swagger
        if: ${{ steps.find.outputs.regenerate == 'true'}}
        run: |
          set -x
          ./services/frontend/resources/build_aggregated_openapi.sh --run-services --set-version

          # Commit the openapi.json if it changed
          generated="services/frontend/resources/openapi.json"
          if [[ -n $(git status -s $generated) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add $generated
            git commit -m "Updated frontend openapi.json/swagger"
            git push
          fi

  build-wheels:
    name: "Build wheels"
    needs: build-frontend
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        service: # all services must be under the services/ folder
          - adgs
          - cadip
          - catalog
          - common
          - frontend
          - osam
          - prip
          - staging
    outputs:
      version_name: ${{ steps.outputs.outputs.version_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # so that Dunamai produce the correct version
      - id: build-wheel
        uses: RS-PYTHON/actions/.github/actions/build-wheel@feat-rspy964/push-latest-after-tests
        with:
          package_directory: "services/${{ matrix.service }}"
      - id: outputs
        # The version name should be the same for all services. Save it only once for any service.
        if: ${{ matrix.service == 'adgs' }}
        run: set -x; echo "version_name=${{ steps.build-wheel.outputs.version_name }}" >> "$GITHUB_OUTPUT"

  set-env:
    name: Set environment
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: build-wheels
    outputs:
      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
      docker_tags: ${{ steps.set-binary-env.outputs.docker_tags }}
      docker_temp_tag: ${{ steps.set-binary-env.outputs.docker_temp_tag }}
      debug_mode: ${{ steps.set-binary-env.outputs.debug_mode }}
    steps:
      - id: set-binary-env
        name: Call action 'set-binary-env'
        uses: RS-PYTHON/actions/.github/actions/set-binary-env@feat-rspy964/push-latest-after-tests
        with:
          wheel_version_name: ${{ needs.build-wheels.outputs.version_name }}
          manual_tag: ${{ github.event.inputs.docker_tag }}

  publish-docker-images:
    name: "Build and publish Docker images"
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    needs: set-env
    permissions:
      security-events: write # needed for github/codeql-action/upload-sarif
      packages: write # needed for 'docker push'
    outputs:
      latest_or_branch_tag: ${{ steps.publish-docker.outputs.latest_or_branch_tag }} # same value for all images
    strategy:
      matrix:
        image:
          - adgs
          - cadip
          - catalog
          - frontend
          - osam
          - prip
          - staging
          - staging-dask-k8s
          - staging-dask-local

        # Options specific to each image.
        # whl_pattern is a glob pattern to download the right binary wheels:
        # rs_server_adgs-<version>.whl, rs_server_cadip-<version>.whl, ...
        # Other options are from the publish-docker action.
        include:
          - image: adgs
            whl_pattern: "{rs_server_adgs-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/adgs/.github/Dockerfile
            image_suffix: rs-server-adgs
          - image: cadip
            whl_pattern: "{rs_server_cadip-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/cadip/.github/Dockerfile
            image_suffix: rs-server-cadip
          - image: catalog
            whl_pattern: "{rs_server_catalog-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/catalog/.github/Dockerfile
            image_suffix: rs-server-catalog
          - image: frontend
            whl_pattern: "rs_server_frontend-*.whl"
            dockerfile: ./services/frontend/.github/Dockerfile
            image_suffix: rs-server-frontend
          - image: osam
            whl_pattern: "{rs_server_osam-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/osam/.github/Dockerfile
            image_suffix: rs-server-osam
          - image: prip
            whl_pattern: "{rs_server_prip-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/prip/.github/Dockerfile
            image_suffix: rs-server-prip
          - image: staging
            whl_pattern: "{rs_server_staging-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/staging/.github/Dockerfile
            image_suffix: rs-server-staging
          - image: staging-dask-k8s
            whl_pattern: "{rs_server_staging-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/staging/.github/Dockerfile.dask-staging
            image_suffix: dask/staging/k8s
            build_args: "BASE_IMAGE_TARGET=k8s"
          - image: staging-dask-local
            whl_pattern: "{rs_server_staging-*.whl,rs_server_common-*.whl}"
            dockerfile: ./services/staging/.github/Dockerfile.dask-staging
            image_suffix: dask/staging/local
            build_args: "BASE_IMAGE_TARGET=local"

    steps:
      - uses: actions/checkout@v6
      - name: Download .whl dependencies
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ matrix.whl_pattern }}
          path: ./build_context_path
          merge-multiple: true
      - if: ${{ matrix.image == 'frontend' }}
        name: Copy entrypoint script
        run: cp ./services/frontend/.github/entrypoint_frontend.sh ./build_context_path
      - name: Copy Dockerfile requirements
        run: cp -t ./build_context_path ./.github/scripts/layer-cleanup.sh ./.github/scripts/restore-apt.sh

      - name: Handle debug mode
        env:
          DEBUG_MODE: ${{ needs.set-env.outputs.debug_mode }}
          BRANCH_NAME: ${{ needs.set-env.outputs.branch_name }}
          DOCKERFILE: ${{ matrix.dockerfile }}
        run: |
          set -x

          # Replace some parts of the Dockerfile depending on wether we're in debug mode or not.
          # It would be cleaner to use 'if' blocks in the Dockerfile but this doesn't exist...
          if [[ $DEBUG_MODE == true ]]; then
            cp -t ./build_context_path ./.github/scripts/git_debug_image.sh
            commands=$(cat << EOF
          USER root
          COPY ./git_debug_image.sh ./restore-apt.sh /usr/local/bin/
          # Use ';' not '&&' because they are not well handled by awk.
          RUN set -e; \
              cd /usr/local/bin/; \
              chmod u+x ./git_debug_image.sh ./restore-apt.sh; \
              ./git_debug_image.sh $BRANCH_NAME; \
              rm -f ./git_debug_image.sh ./restore-apt.sh
          WORKDIR /home/user/rs-server
          EOF
            )
            # Use awk instead of sed for multiline replace, see: https://stackoverflow.com/a/10107668
            awk -v r="$commands" '{gsub(/# \[DEBUG_MODE_COMMANDS\]/,r)}1' $DOCKERFILE > tmp
            mv tmp $DOCKERFILE
            sed -i "s@\[DEBUG_MODE_RELOAD\]@--reload@g" $DOCKERFILE
            sed -i "s@\[DEBUG_MODE_RELOAD_FRONTEND\]@--reload@g" $DOCKERFILE
            sed -i "s@# \[DEBUG_MODE_RELOAD_CATALOG\]@ENV RELOAD=true@g" $DOCKERFILE

          # No debug mode: just remove these tags from the dockerfile
          else
            sed -i "s@# \[DEBUG_MODE_COMMANDS\]@@g" $DOCKERFILE
            sed -i "s@, \"\[DEBUG_MODE_RELOAD\]\"@@g" $DOCKERFILE
            sed -i "s@\[DEBUG_MODE_RELOAD_FRONTEND\]@@g" $DOCKERFILE
            sed -i "s@# \[DEBUG_MODE_RELOAD_CATALOG\]@@g" $DOCKERFILE
          fi
          cat $DOCKERFILE

      - run: ls ./build_context_path
      - id: publish-docker
        uses: RS-PYTHON/actions/.github/actions/publish-docker@feat-rspy964/push-latest-after-tests
        with:
          dockerfile: ${{ matrix.dockerfile }}
          build_context_path: ./build_context_path
          image_basename: ${{ github.repository_owner }}/
          image_suffix: ${{ matrix.image_suffix }}
          image_tags: ${{
            case(needs.set-env.outputs.docker_temp_tag != '',
            needs.set-env.outputs.docker_temp_tag,
            needs.set-env.outputs.docker_tags) }} # pass the temp tag if defined, else the nominal tags
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_args: ${{ matrix.build_args }}
      - uses: cloudposse/github-action-matrix-outputs-write@81ea135d4c4f90a5220bb38304380073c571dbb8
        with:
          matrix-step-name: publish-docker-images
          matrix-key: ${{ matrix.image }}
          outputs: |
            docker_images: ${{ steps.publish-docker.outputs.docker_images }}

  get-pushed-images:
    name: Get pushed Docker image names
    needs: [set-env, publish-docker-images]
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      pushed_images: ${{ steps.read.outputs.pushed_images }}
    steps:
      - id: read-matrix-outputs
        if: ${{ needs.set-env.outputs.docker_temp_tag != '' }} # only if a temp Docker tag has been set
        uses: cloudposse/github-action-matrix-outputs-read@ddb62566e896c85614f5eeec2daa43d6d1dc6cb0
        with:
            matrix-step-name: publish-docker-images
      - id: read
        if: ${{ needs.set-env.outputs.docker_temp_tag != '' }}
        run: |
          set -x
          # Docker images that have been pushed
          # e.g. {"docker_images": {"cadip": "<cadip_image>", "adgs": "<adgs_image>" }}
          json_images='${{ steps.read-matrix-outputs.outputs.result }}' # use simple quotes, not double quotes !
          pushed_images=$(echo "$json_images" | jq -r .docker_images[] | paste -sd,) # separate values with ','

          echo pushed_images="$pushed_images" >> "$GITHUB_OUTPUT"

  # Test rs-demo with the new Docker images
  test-demo:
    name: Test rs-demo
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: [set-env, publish-docker-images, get-pushed-images]
    permissions:
     packages: write # needed for 'docker push'
    steps:
      - name: Log into Docker registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test rs-demo
        env:
          BRANCH_NAME: ${{ needs.set-env.outputs.branch_name }}
          DOCKER_TAG: ${{ needs.publish-docker-images.outputs.latest_or_branch_tag }}
        run: |
          set -x

          # Clone the rs-demo repository
          git clone https://github.com/RS-PYTHON/rs-demo.git
          cd rs-demo

          # Run the rs-demo local mode using the newly created docker images
          ./test-rs-demo.sh

      # If we used a temp docker tag, and only if the tests succeeded, then
      # we tag the images with the real tags and push them.
      - name: Tag and push Docker images
        if: ${{ needs.set-env.outputs.docker_temp_tag != '' }}
        uses: RS-PYTHON/actions/.github/actions/tag-push-docker@feat-rspy964/push-latest-after-tests
        with:
          old_docker_images: ${{ needs.get-pushed-images.outputs.pushed_images }}
          new_tags: ${{ needs.set-env.outputs.docker_tags }}

  publish-wheels-pypi:
    name: "Publish wheels and sdists to PyPI"
    if: (github.actor != 'dependabot[bot]') && (github.event_name == 'push') && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [test-demo] # only if the tests succeeded
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download dist dependencies
        uses: actions/download-artifact@v8
        with:
          path: ./dist
          merge-multiple: true
      - name: Publish wheel and sdist packages
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          skip-existing: true
          packages-dir: ./dist
          verbose: true
