name: Publish wheels and Docker images

# TODO: is it possible to run this workflow only if the check-code-quality workflow has completed successfully ?
# I've tried workflow_run but see:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
# Note: This event will only trigger a workflow run if the workflow file is on the default branch.

# Run workflow only for new git tags (including hierarchical tags like v1.0/beta), or manually
on:
  push:
    # tags:
    #   - '**'
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ghcr.io/rs-python/rs-server # TODO: use ${{ github.repository }} in lowercase ?

jobs:

  ##################
  # Publish wheels #
  ##################

  rs-server-whl:
    runs-on: ubuntu-latest
    name: "'rs-server' wheel"
    outputs:
      version_name: ${{ steps.publish-wheel.outputs.version_name }}
      package_name: ${{ steps.publish-wheel.outputs.package_name }}
    continue-on-error: true # TODO remove when the right python repo will be set
    steps:
      - uses: actions/checkout@v4
      - id: publish-wheel
        uses: ./.github/actions/publish-wheel

  services-common-whl:
    runs-on: ubuntu-latest
    name: "'services/common' wheel"
    outputs:
      version_name: ${{ steps.publish-wheel.outputs.version_name }}
      package_name: ${{ steps.publish-wheel.outputs.package_name }}
    continue-on-error: true # TODO remove when the right python repo will be set
    steps:
      - uses: actions/checkout@v4
      - id: publish-wheel
        uses: ./.github/actions/publish-wheel
        with:
          package_directory: services/common

  services-cadip-whl:
    runs-on: ubuntu-latest
    name: "'services/cadip' wheel"
    outputs:
      version_name: ${{ steps.publish-wheel.outputs.version_name }}
      package_name: ${{ steps.publish-wheel.outputs.package_name }}
    continue-on-error: true # TODO remove when the right python repo will be set
    steps:
      - uses: actions/checkout@v4

      # Hack the pyproject.toml. TODO: find a cleaner to do this.
      # Replace '<dep> = {path = "./relative/path", develop = true}' by '<dep> = "*"'.
      - run: sed -i "s|^.*rs-server-common.*path.*$|rs-server-common = \"\*\"|g"  services/cadip/pyproject.toml

      - id: publish-wheel
        uses: ./.github/actions/publish-wheel
        with:
          package_directory: services/cadip

  #########################
  # Publish Docker images #
  #########################

  rs-server-img:
    runs-on: ubuntu-latest
    name: "'rs-server' Docker image"
    needs: [rs-server-whl]
    steps:
      - uses: actions/checkout@v4

      # Download .whl files into ./dist/
      # - run: mkdir -p ./dist
      - name: Download .whl dependencies
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.rs-server-whl.outputs.package_name }}
          path: ./dist

      # Replace invalid characters in the Docker version name, e.g. 1.2.3a4+dev1a2b3c4d becomes 1.2.3a4.dev1a2b3c4d
      - run: echo "docker_version_name=$(echo ${{ needs.rs-server-whl.outputs.version_name }} | tr + .)" >> $GITHUB_ENV

      - uses: ./.github/actions/publish-docker
        with:
          dockerfile: Dockerfile.POC
          build_context_path: ./dist
          version_name: ${{ env.docker_version_name }} # from above step
